// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkB0hL-AQQCkAKwidePgyat32qawbvsYM',
    appId: '1:1046585687289:web:af7a8308cd08ab16d63628',
    messagingSenderId: '1046585687289',
    projectId: 'e-commerce-cd1d9',
    authDomain: 'e-commerce-cd1d9.firebaseapp.com',
    storageBucket: 'e-commerce-cd1d9.firebasestorage.app',
    measurementId: 'G-LH686LMY5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8Ck7HBdm1aP-tg4LAEOF_uUU2kpIdj6w',
    appId: '1:1046585687289:android:9bf0d1424030d773d63628',
    messagingSenderId: '1046585687289',
    projectId: 'e-commerce-cd1d9',
    storageBucket: 'e-commerce-cd1d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi_74Dojg7aw1wMY7lm3fh20JU4ESUr9c',
    appId: '1:1046585687289:ios:23b55bb98f216a36d63628',
    messagingSenderId: '1046585687289',
    projectId: 'e-commerce-cd1d9',
    storageBucket: 'e-commerce-cd1d9.firebasestorage.app',
    iosBundleId: 'com.example.shopyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi_74Dojg7aw1wMY7lm3fh20JU4ESUr9c',
    appId: '1:1046585687289:ios:23b55bb98f216a36d63628',
    messagingSenderId: '1046585687289',
    projectId: 'e-commerce-cd1d9',
    storageBucket: 'e-commerce-cd1d9.firebasestorage.app',
    iosBundleId: 'com.example.shopyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkB0hL-AQQCkAKwidePgyat32qawbvsYM',
    appId: '1:1046585687289:web:701e508ea9c9616bd63628',
    messagingSenderId: '1046585687289',
    projectId: 'e-commerce-cd1d9',
    authDomain: 'e-commerce-cd1d9.firebaseapp.com',
    storageBucket: 'e-commerce-cd1d9.firebasestorage.app',
    measurementId: 'G-YSMZ218ZNB',
  );

}